client_config_backend: settings
client_config:
  client_id: 890426931364-72ate30hsru3tu2orq40tvacod40f6i8.apps.googleusercontent.com
  client_secret: cdJDUdh5lR3b3lXJMAsFKOSR

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install